### ISSUE TITLE
Translations for Encryption Option(s)

### ISSUE THREAD

**Issue by Andanan** [bndw/wifi-card#106]
Currently the texts/translations of the encryption options are fixed. But at least for `None` it would be nice to have a translation.
Maybe some locales treat the names of the algorithms specially but i think those would be ok as they are for most locales.

![image](https://user-images.githubusercontent.com/25869706/126419202-6095ec25-bb40-41d2-b953-0266d8e78b21.png)

**Comment by olekstomek** [comment]
From a different point of view, I wonder if it is worth translating something that is not visible on the printed card. https://github.com/bndw/wifi-card/pull/74#issuecomment-882931174

**Comment by bndw** [comment]
I think it's either (1) rely on the browser for translation or (2) translate everything. Since we're already 9 languages in to option (2) I think we should translate `None`. 

Related: We'll need to come up with a good strategy for updating the various languages when there is a text change or addition.

**Comment by olekstomek** [comment]
`(1) rely on the browser for translation `
https://github.com/bndw/wifi-card/pull/74#issuecomment-884348733

`Related: We'll need to come up with a good strategy for updating the various languages when there is a text change or addition.`
Yes, this topic was discussed in this PR https://github.com/bndw/wifi-card/pull/74 (from this comment https://github.com/bndw/wifi-card/pull/74#issuecomment-882931174 - different strategies/ideas).

**Comment by bndw** [comment]
OK, here's what we'll do:

Since this issue is just asking to additionally translate the word `None`, that's the solution. We can use Google Translate or similar to do the backfill, open the PR, and tag the original translators to verify. If they don't respond we'll merge and triage any issues that may arise later.

**Comment by Andanan** [comment]
Sounds good to me

**Comment by olekstomek** [comment]
Yeah, it seems that it will be the most optimal way

**Comment by Mejans** [comment]
In both Catalan and Occitan this would be «Cap» if this helps ;)
