### ISSUE TITLE
"Unable to join the network" error on iOS 13.5

### ISSUE THREAD

**Issue by welby12** [bndw/wifi-card#2]
I really wanted this to work, but for my friends on iOS (including me) it doesn't. You can hit "join network", but it will always throw the error "Unable to join the network '[name]'" 

Have double checked for typos, and tried various times on various devices

**Comment by bndw** [comment]
Hi, sorry to hear you're having trouble.

A couple quick thoughts-- does your network name have any special characters? If so, you may be impacted by https://github.com/bndw/wifi-card/issues/3. If your network name does not have special characters I'd recommend generating a QR code for your WiFi with a different QR code generator, as a test. This should help identify where the problem lies.

Here's how to test this:
1. Manually format the QR code data string as follows: 
    ```
    WIFI:T:WPA;S:YOUR_NETWORK_NAME;P:$YOUR_PASSWORD;;
    ```
    So if your network name is `GuestWiFi` and the password is `welcome`, you'd use:
    ```
    WIFI:T:WPA;S:GuestWIFI;P:welcome;;
    ```
2. Copy and paste that string into an online QR Code generator you're comfortable with. You can find some by searching "QR code generator". Consider resetting the password after this test, unless you trust the site you use.
3. Point your iPhone camera and see if you have the same problem.

If the problem persists, then I believe it's related to your network configuration or iOS.

**Comment by welby12** [comment]
Thanks for the prompt reply, was able to get it working! The issue was that the password has backslashes in it, but by putting backslashes before, well... the backslashes, it worked. 

Would be nice if this was resolved somehow in the future, since it makes the password incorrect if I print out the card and someone is reading it. 

Regardless, thanks for your work on this generator!

**Comment by bndw** [comment]
@welby12 You should be able to use a password with backslashes in it now, this was fixed in https://github.com/bndw/wifi-card/pull/6
