### ISSUE TITLE
Missing spaces in radio and checkbox in RTL

### ISSUE THREAD

**Issue by AhmedElTabarani** [bndw/wifi-card#250]
Screenshot:
![image](https://user-images.githubusercontent.com/69223584/189579593-9f0637ff-4f9d-4f0b-827b-561167acea6e.png)

**Comment by bndw** [comment]
Hi @AhmedElTabarani, thanks for the report. I'm guessing the UI library we're using (evergreen-ui) is missing some padding-right for RTL support. 

We could probably resolve this by adding a CSS rule that adds some padding-right to these inputs. Feel free to open a PR, otherwise I'll look into this when I get a chance.
