### ISSUE TITLE
Make the language names consistent

### ISSUE THREAD

**Issue by Teraskull** [bndw/wifi-card#80]
Right now the dropdown languages are written in three different ways:
1. Locale name
2. Full name in that language
3. Language code
![image](https://user-images.githubusercontent.com/24798198/126068021-208a8112-aa36-4e08-a8b6-4731d76ed7dc.png)

My suggestion is to have the names show like in [Ventoy](https://github.com/ventoy/Ventoy):
![image](https://user-images.githubusercontent.com/24798198/126068094-75d114e7-c486-411b-9f5a-1565da2810b8.png)
The full name in English, and the translated name in brackets.

For i18n, the international locale codes should be used, as found [here](http://www.lingoes.net/en/translator/langcode.htm).
```js
'en-US': {
    translation: {
...
```

**Comment by A-Tokyo** [comment]
@Teraskull Awesome initiative! 

I'd advice for `latinName - nativeName` instead of `latinName - (nativeName)` simply to account for `RTL` languages. Using the newly proposed version would make the native RTL languages look native in the dropdown due to right alignment. The extra brackets mess up that alignment.

Excited for this! ( :
