### ISSUE TITLE
It dosen't work in wechat scanning!

### ISSUE THREAD

**Issue by IcaursWing** [bndw/wifi-card#88]
Just as what title said.

**Comment by olekstomek** [comment]
I don't use this messenger, but from what I found quickly [WeChat scans the qr code to add someone to my contacts](https://help.wechat.com/cgi-bin/micromsg-bin/oshelpcenter?opcode=2&id=160527qrfrfb160527rf3e6v&lang=en&plat=2&Channel=helpcenter), maybe the qr code is still being used for something else. So the problem is with this messenger, I guess it expects a different data format. This qr code is a quick connection to a WiFi network and has a specific structure for this. Use an application to scan qr codes or preferably a native application - I mean the camera application which in many smartphones automatically scans qr code.

**Comment by noahhefner** [comment]
I also do not use WeChat, but from [this article](https://www.softwarert.com/scan-qr-code-wechat-iphone/), it seems like the WeChat scanner will only read QR codes that point to a URL. Best option is to use your phone's built in camera app to scan the code. **Any phone running Android 8/iOS 11 or higher has this feature built in by default** and is likely much faster than WeChat anyway.

**Comment by olekstomek** [comment]
I think this issue can be closed.

**Comment by Baoyuantop** [comment]
WeChat scan code does not have this function, just use the camera application

**Comment by IcaursWing** [comment]
Thank you very much for the explanation and quick response. But the truth of our using environment is that almost everyone use wechat scanner to scan the qr code everywhere.

**Comment by olekstomek** [comment]
But you can scan any qr codes in this app? After scanning this code:
![test](https://user-images.githubusercontent.com/26818304/126555024-71bb2a16-b117-43bf-9ee4-05b3b8189a7d.png)
do you see the text:
`Test. It Works!`?

Look https://github.com/bndw/wifi-card/issues/39#issue-941814493 that it's a standard for creating a qr code that is understood by mobile systems and allows you to automatically connect to a WiFi network. There is no way to say otherwise and it is the WeChat application that must understand this qr code.
Got a bug in this app after scanning or are you just trying to scan and can't see the result?

**Comment by IcaursWing** [comment]
There is no bug that I want to issue, just find a good way to connect to a WiFi network in your project, and the qr code work well! Although I find the native camera application of my phone which doesn't support scanning qr code. Sadly... If this WiFi-card can be scanned by WeChat, it can be widely used in people's life. Because people won't use the native camera application by the first time until you told them to do so. People around my living environment will use WeChat to do the scanning as first choice, and some android phone's native camera application doesn't support scanning. By the way, the project is very good for study.

**Comment by olekstomek** [comment]
We have one standard of QR code (for connecting automatically to WiFI) that should be understood by devices and applications such as WeChat.  Having printed a QR code, it can only have one value for all applications, devices, etc. Note that this is one QR code that Android and iOS understand.  There is no way to create special QR code for WeChat.

The only thing I can advise you is contacting WeChat support.

**Comment by Baoyuantop** [comment]
This is a detailed description：
https://developers.weixin.qq.com/doc/offiaccount/en/WiFi_via_WeChat/WiFi_Software_Service_Management_API.html

At present, this method cannot be simply implemented in this project.
