### ISSUE TITLE
SonarLint - issues on master branch

### ISSUE THREAD

**Issue by olekstomek** [bndw/wifi-card#93]
Maybe it's worth noting:
- Critical
https://github.com/bndw/wifi-card/blob/0eea7b56a67f40c1cb8520ecb41fae19966be8ad/src/components/Card.js#L6
```
Refactor this function to reduce its Cognitive Complexity from 34 to the 15 allowed. [+27 locations]sonarlint(javascript:S3776)
Cognitive Complexity of functions should not be too high (javascript:S3776)
Cognitive Complexity is a measure of how hard the control flow of a function is to understand. Functions with high Cognitive Complexity will be difficult to maintain.
```

- Minor:
https://github.com/bndw/wifi-card/blob/0eea7b56a67f40c1cb8520ecb41fae19966be8ad/src/components/Card.js#L21
```
Expected a `for-of` loop instead of a `for` loop with this simple iteration.sonarlint(javascript:S4138)
"for of" should be used with Iterables (javascript:S4138)
If you have an iterable, such as an array, set, or list, your best option for looping through its values is the for of syntax. Use a counter, and ... well you'll get the right behavior, but your code just isn't as clean or clear.
```

**Comment by bndw** [comment]
1. Not interested in refactoring `export const Card`. In general that's lint rule is fine advice, but in this case I don't agree.
2. `for-of` seems like a fine change. I wrote the traditional loop because I don't write a ton of JS and didn't realize `for-of` was an option. If you want to make the change I'd be happy to accept it. I think it'd be:
    ```js
    for (let c of v) {
    ```

**Comment by olekstomek** [comment]
Solution was merged so I'm closing this issue.
